#!/bin/sh

if ! [[ "$OSTYPE" == "darwin"* ]]; then
	exit 0
fi

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR=$FRESH_PATH/installers/homebrew

if [ ! -d $DIR ]; then
	exit 0
fi

if [ ! -d ~/.fresh ]; then
	echo 'Install fresh first'
	exit 1
fi

command -v brew >/dev/null 2>&1
if [ "$?" -ne "0" ]; then
    echo 'Install Homebrew: http://brew.sh/'
    exit 1
fi

updated="no"
function update {
	if [ "$updated" != "done" ]; then
		echo "Updating brew before installing new stuff"
		brew update
		brew doctor
		brew upgrade
	fi
	updated="done"
}

# Install Missing Taps
#
if [ -f $DIR/taps ]; then
	brew tap > /tmp/installed
	cat $DIR/taps | tr -d "\t " | cut -d "#" -f 1 | sort -u > /tmp/toinstall
	TO_INSTALL=$(comm -13 /tmp/installed /tmp/toinstall)

	if [ ! -z "${TO_INSTALL}" ]; then
		echo "Missing brew taps should be installed"
		update
		for TAP in ${TO_INSTALL}; do
			echo "Installing tap $TAP"
			brew tap ${TAP}
		done
	else
		echo "All brew taps are already installed"
	fi
fi

# Install Missing Homebrew formulas
#
if [ -f $DIR/formulas ]; then
	brew list > /tmp/installed
	cat $DIR/formulas | tr -d "\t " | cut -d "#" -f 1 | sort -u > /tmp/toinstall
	TO_INSTALL=$(comm -13 /tmp/installed /tmp/toinstall)

	if [ ! -z "${TO_INSTALL}" ]; then
		echo "Missing brew formulas should be installed"
		update
		echo "Installing brew formulas ${TO_INSTALL}"
		brew install ${TO_INSTALL}
	else
		echo "All brew formulas are already installed"
	fi
fi

# Install Missing Cask formulas
#
if [ -f $DIR/cask-formulas ]; then
	brew cask list > /tmp/installed
	cat $DIR/cask-formulas | tr -d "\t " | cut -d "#" -f 1 | sort -u > /tmp/toinstall
	TO_INSTALL=$(comm -13 /tmp/installed /tmp/toinstall)

	if [ ! -z "${TO_INSTALL}" ]; then
		echo "Missing brew cask formulas should be installed"
		update
		echo "Installing brew cask formulas ${TO_INSTALL}"
		brew cask install ${TO_INSTALL}
	else
		echo "All brew cask formulas are already installed"
	fi
fi
