#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"

RED='\033[0;31m'
LIGHT_GREEN='\033[1;32m'
NC='\033[0m' # No Color

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Load fresh shell in order for environment variables sourced by fresh to be available during installation phase
source $FRESH_PATH/build/shell.sh || true

# find the installers and run them iteratively
compgen -c | grep "^fresh-install-" | grep -v $(basename "$0") | sed "s/^fresh-install-//" | while read installer ; do
#	echo $installer
	printf "Running ${LIGHT_GREEN}$installer${NC} installer\n"
	sh -c "fresh-install-${installer}"
done
 
